blueprint:
  name: Water Leak Notification (iPhone + Email via SMTP)
  description: Sends an iOS Critical Alert and an email via SMTP when a water leak is detected. Allows overriding the recipient(s) in the automation.
  domain: automation
  input:
    water_sensor:
      name: Water Leak Sensor
      description: The leak-detecting binary sensor.
      selector:
        entity:
          domain: binary_sensor
    notify_device:
      name: Notify Device (mobile app)
      description: The iOS device to receive a Critical Alert.
      selector:
        device:
          integration: mobile_app
    email_service:
      name: Email Notify Service
      description: The SMTP notify service name (e.g., notify.zoho_smth).
      default: "notify.zoho_smth"
      selector:
        text: {}
    email_recipients:
      name: Override Recipient(s) (Optional)
      description: Comma-separated email addresses. Leave empty to use default from SMTP config.
      default: ""
      selector:
        text: {}
    custom_prefix:
      name: Message Prefix (Optional)
      description: Text prefixed to the notification.
      default: "🚨 Water leak detected!"
      selector:
        text: {}

trigger:
  - platform: state
    entity_id: !input water_sensor
    to: "on"

variables:
  sensor_name: "{{ state_attr(trigger.entity_id, 'friendly_name') or trigger.entity_id }}"
  time_now: "{{ now().strftime('%H:%M:%S') }}"
  prefix: !input custom_prefix
  final_message: "{{ prefix }}\nSensor: {{ sensor_name }}\nTime: {{ time_now }}"
  recipients: "{{ (!input email_recipients) | default('', true) }}"

action:
  - parallel:
      # iOS Critical Alert
      - device_id: !input notify_device
        domain: mobile_app
        type: notify
        message: "{{ final_message }}"
        data:
          push:
            sound:
              name: default
              critical: 1
              volume: 1.0

      # Email via SMTP
      - service: !input email_service
        data:
          title: "🚨 Water Leak Alert"
          message: "{{ final_message }}"
          {% if recipients != "" %}
          target:
            - "{{ recipients }}"
          {% endif %}

mode: single
