blueprint:
  name: Water Leak Notification
  description: Sends a Critical Alert to iPhone and an email when a water leak is detected.
  domain: automation
  input:
    water_sensor:
      name: Water Leak Sensor
      description: The binary sensor that detects a water leak.
      selector:
        entity:
          domain: binary_sensor
    notify_device:
      name: Notify Device
      description: The mobile device to send the iOS Critical Alert to.
      selector:
        device:
          integration: mobile_app
    email_target:
      name: Email Target
      description: The email address or notify service to send the alert to.
      selector:
        entity:
          domain: notify
    custom_prefix:
      name: Message Prefix (Optional)
      description: Text to appear before the sensor name and time.
      default: "🚨 Water leak detected!"
      selector:
        text: {}

trigger:
  - platform: state
    entity_id: !input water_sensor
    to: "on"

variables:
  sensor_name: "{{ state_attr(trigger.entity_id, 'friendly_name') or trigger.entity_id }}"
  time_now: "{{ now().strftime('%H:%M:%S') }}"
  prefix: !input custom_prefix
  final_message: "{{ prefix }}\nSensor: {{ sensor_name }}\nTime: {{ time_now }}"

action:
  - parallel:
      - device_id: !input notify_device
        domain: mobile_app
        type: notify
        message: "{{ final_message }}"
        data:
          push:
            sound:
              name: default
              critical: 1
              volume: 1.0
      - service: notify.send_message
        target:
          entity_id: !input email_target
        data:
          message: "{{ final_message }}"
          title: "🚨 Water Leak Alert"

mode: single
