blueprint:
  name: Water Leak Notification v0.2
  description: Sends a critical iOS alert and a rich HTML-formatted email via SMTP when a water leak is detected.
  domain: automation
  input:
    water_sensor:
      name: Water Leak Sensor
      description: Binary sensor that detects water leakage.
      selector:
        entity:
          domain: binary_sensor
    notify_device:
      name: Notify Device (mobile app)
      description: The iOS device to receive a Critical Alert.
      selector:
        device:
          integration: mobile_app
    email_service:
      name: Email Notify Service
      description: The SMTP notify service (e.g., notify.zoho_smth).
      default: "notify.zoho_smth"
      selector:
        text: {}
    email_recipients:
      name: Override Recipient(s) (Optional)
      description: Comma-separated email addresses. Leave blank to use default from SMTP config.
      default: ""
      selector:
        text: {}
    custom_prefix:
      name: Message Prefix (Optional)
      description: Text prefixed to notifications.
      default: "🚨 Water leak detected!"
      selector:
        text: {}

trigger:
  - platform: state
    entity_id: !input water_sensor
    to: "on"

variables:
  sensor_name: "{{ state_attr(trigger.entity_id, 'friendly_name') or trigger.entity_id }}"
  location: "{{ area_name(trigger.entity_id) or 'Unknown location' }}"
  time_now: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"
  prefix: !input custom_prefix
  final_message: "{{ prefix }}\nSensor: {{ sensor_name }}\nLocation: {{ location }}\nTime: {{ time_now }}"
  recipients_list: >-
    {% set r = email_recipients | trim %}
    {% if r != "" %}
      {{ r.split(',') | map('trim') | list }}
    {% else %}
      {{ none }}
    {% endif %}

action:
  - parallel:
      # iOS Critical Alert
      - device_id: !input notify_device
        domain: mobile_app
        type: notify
        message: "{{ final_message }}"
        data:
          push:
            sound:
              name: default
              critical: 1
              volume: 1.0

      - service: !input email_service
        message: "{{ final_message }}"
        data:
          title: "🚨 WATER LEAK ALERT – {{ sensor_name }}"
          html: >
            <!DOCTYPE html>
            <html>
            <head>
              <meta charset="UTF-8">
              <style>
                body { font-family: Arial, sans-serif; background: #f4f4f4; margin: 0; padding: 0; }
                .container { max-width: 600px; margin: auto; background: #fff; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
                .header { background-color: #d32f2f; color: #fff; padding: 20px; text-align: center; font-size: 24px; }
                .content { padding: 20px; color: #333; line-height: 1.5; }
                .alert-box { border: 2px solid #d32f2f; background: #ffebee; padding: 15px; border-radius: 4px; margin-bottom: 20px; }
                .footer { background: #eeeeee; text-align: center; padding: 10px; font-size: 12px; color: #777; }
              </style>
            </head>
            <body>
              <div class="container">
                <div class="header">🚨 WATER LEAK ALERT 🚨</div>
                <div class="content">
                  <div class="alert-box">
                    <strong>Sensor:</strong> {{ sensor_name }}<br>
                    <strong>Location:</strong> {{ location }}<br>
                    <strong>Detected At:</strong> {{ time_now }}
                  </div>
                  <p><strong>Action Recommended:</strong> Inspect immediately and shut off the water supply if needed. Potential for flooding exists.</p>
                </div>
                <div class="footer">
                  Automated alert from Home Assistant.<br>
                  Please do not reply.
                </div>
              </div>
            </body>
            </html>      
          recipients: "{{ recipients_list | default(none) }}"          

mode: single
