blueprint:
  name: Water Leak Detection
  description: Send notification when water leak is detected
  domain: automation
  input:
    water_sensor:
      name: Water Leak Sensor
      description: Select the water leak sensor
      selector:
        entity:
          domain: binary_sensor
    notify_device:
      name: Mobile Device
      description: Select your mobile device for notifications
      selector:
        device:
          integration: mobile_app

mode: single

trigger:
  - type: turned_on
    entity_id: !input water_sensor
    domain: binary_sensor
    trigger: entity

condition: []

action:
  - device_id: !input notify_device
    domain: mobile_app
    type: notify
    message: Water leak