blueprint:
  name: Water Leak Detection and Alert
  description: >
    Creates an automation for IKEA BADRING water leak sensors that:
    - Sends mobile push notifications
    - Shows persistent notifications in HA
    - Sends email alerts
    - Changes selected lights to red
  domain: automation
  input:
    water_sensor:
      name: Water Leak Sensor
      description: Select the water leak sensor to monitor
      selector:
        entity:
          domain: binary_sensor
    notification_email:
      name: Email Address
      description: Email address to send notifications to
      selector:
        text:
    notify_device:
      name: Mobile Device
      description: Select your mobile device notification service
      selector:
        device:
          integration: mobile_app
    

trigger:
  - platform: state
    entity_id: !input water_sensor
    to: "on"

variables:
  sensor_name: "{{ states[trigger.entity_id].name }}"
  sensor_area: "{{ states[trigger.entity_id].attributes.friendly_name }}"
  detection_time: "{{ now().strftime('%H:%M:%S') }}"
  notification_title: "⚠ Water Leak Detected!"
  notification_message: >
    Water detected by {{ sensor_name }} in {{ sensor_area }} at {{ detection_time }}

condition: []

action:
  - service: !input notify_device
    data:
      title: "{{ notification_title }}"
      message: "{{ notification_message }}"
      data:
        push:
          category: "water_leak"
          importance: high
          priority: high
          ttl: 0
          tag: "water_leak_{{ trigger.entity_id }}"
          group: water_leak
          color: "#ff0000"
          sticky: true
          vibration: true

  - service: persistent_notification.create
    data:
      title: "{{ notification_title }}"
      message: "{{ notification_message }}"
      notification_id: "water_leak_{{ trigger.entity_id }}"

  - service: notify.email
    data:
      title: "{{ notification_title }}"
      message: "{{ notification_message }}"
      target: "{{ input.notification_email }}"
