blueprint:
  name: Water Leak Notification
  description: Send a mobile notification when a water leak sensor is triggered.
  domain: automation
  input:
    water_leak_sensor:
      name: Water Leak Sensor
      description: The binary sensor that detects a water leak.
      selector:
        entity:
          domain: binary_sensor
    notify_device:
      name: Notify Device
      description: The mobile device to send the notification to.
      selector:
        device:
          integration: mobile_app
    message:
      name: Notification Message
      description: The message to send when a leak is detected.
      default: "Water leak detected!"
      selector:
        text: {}

trigger:
  - platform: state
    entity_id: !input water_leak_sensor
    to: "on"

action:
  - device_id: !input notify_device
    domain: mobile_app
    type: notify
    message: !input message

mode: single
